---
title: "비모수적 검정(Non-parametric test)"
author: "Jaewoo Cho"
date: '2019-05-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 비모수적 검정

- 모수적 검정이 성립하지 않을때 사용하는 검정
    - 분포에 자유로운 검정, 무가정 검정이라고 하는데 엄밀히 말하자면 비모수적 검정들에도 분포에 관한 가정이 존재한다. 다만, 모수적 검정에 비하면 가정이 덜 제한적이다.
    
- 비모수적 검정은 대부분의 자료의 **순위화(ranking)**에 기초
    - 순위화: 자료에 순위를 부여하는 방법. 자료의 점수가 제일 크면 1, 그 다음은 2 이런식으로 부여하고 순위에 대해서 검정을 진행한다.
    
- 종류
    - 독립 t 검정 → 윌콕슨 순위합 검정(만-위트니 검정과 동일)
    - 종속 t 검정 → 윌콕슨 부호순위 검정
    - 일원독립분산분석 → 크러스컬-월리스 검정

## 윌콕슨 순위합 검정(Wilcoxon's rank-sum test) - 독립 t 검정

- 독립 t 검정의 비모수적 방법
- 기본 원리
    - 속한 그룹을 무시하고 가장 낮은 점수를 순위 1로 하여 최저 점수에서 최고 점수로 매긴다.
    - 두 그룹의 차이가 없다면 각 순위합이 거의 비슷할 것이다. (다르다면 차이가 날 것이다.)
    - 동순위라면 순위의 평균을 매긴다.
    
### 윌콕슨 순위합 검정(Wilcoxon's rank-sum test) 순서

1. 각 그룹의 순위합을 매긴다. 
2. 각 그룹의 순위합에서 평균 순위 (mean rank)를 뺀다. (이렇게 하지 않으면 그룹이 클수록 순위합도 커지는 결과)
    - 평균 순위(mean rank): 1에서 그룹 크기까지의 합
3. W = 순위합 - 평균 순위 ⇒ 각 그룹에 대해 W1, W2 값이 나오고 검정통계량으로 두 값 중 작은 값을 사용한다.
4. 검정통계량(W)를 바탕으로 p 값을 계산한다.
    - p 값 계산 방법
        - 참값(exact) 접근 방식 - 몬테카를로 방법(Monte Carlo method)
        - 정규 근사(normal approximation)
        
        
### 몬테카를로 방법(Monte Carlo method) 

- 표본과 부합하는 다수의 자료 집합을 생성하되, 자료들을 정확한 그룹에 넣는 것이 아니라 무작위로 선택한 그룹에 넣는다. 자료가 무작위로 그룹에 배정되므로 귀무가설이 참이다.
- 즉, 귀무가설이 참인 자료에 기초해서 W 값을 계산
- R은 이 과정을 수천번 진행하여 귀무가설이 참일때 나타나는 차이가 자료에 나타난 차이만큼 큰 경우의 횟수를 센다.
- 표본이 크거나 동순위 점수가 존재하면 사용하기 힘들다.

### 정규 근사(normal approximation)

- W 통계량의 표집분포가 정규분포라고 가정
- 그 가정이 성립한다면 z 값을 계산하는 데 쓰이는 표준 오차를 구할 수 있으며, p 값도 구할 수 있다.
- R은 기본적으로 표본이 크거나(40 이상) 동순위 점수가 존재하는 경우 사용한다.
    - R은 기본적으로 연속성 수정 (순위는 1단위 이기 때문에) 실행

